### ISSUE TITLE
Relative path in domain

### ISSUE THREAD

**Issue by orjanb-ne** [factmaven/remove-http#8]
This code adds support for relative paths, if you want to serve the WP site via proxy where the domain is different:

```
-                $website = preg_replace( '/https?:\/\//', '', home_url() );
+                $website = preg_replace( '/^https?:\/\//', '', home_url() );
+                $website = preg_replace('/\/.*$/', '', $website);
```

**Comment by jinksraevan** [comment]
Thanks for the contribution, I'll review and test this snippet and get back to you on it.

**Comment by ethanosullivan** [comment]
@orjanb-ne I'm just getting around to testing out your snippet. Could you provide me an example on how this code works exactly? I'm trying to understand it myself.

**Comment by jinksraevan** [comment]
Updated the code to add support for relative paths.
