### ISSUE TITLE
Only alter links in the frontend

### ISSUE THREAD

**Issue by jinksraevan** [factmaven/remove-http#9]
Source: https://wordpress.org/support/topic/please-only-alter-links-in-the-frontend/

> This plugin would be perfect if: Can we please get this plugin to only alter links which are displayed in the frontend? Now it seems to modify all kind of links, regardless if it’s in the admin or not. That said, it happens by accident to store “//my.domain.tld” within the database which does break links pointing to external ressources. Also having this kind of behaviour within the admin does not create any benefit at all.

**Comment by marbetschar** [comment]
any news on this?

**Comment by ethanosullivan** [comment]
@marbetschar We're releasing a new version of this plugin with new bug fixes and enhancements.

Per this request above, I don't see a use case to exclude the rewrite in admin dashboard. Furthermore, the plugin already ignores any text fields that have a URL in it to prevent the database saving as protocol-relative:

![image](https://user-images.githubusercontent.com/23202467/78502830-0f2e0b00-7731-11ea-99b3-aa0f74bb268d.png)

If there's a specific use case given, we can review this again. Closing this ticket in the meantime.

**Comment by jinksraevan** [comment]
@marbetschar We're releasing a new version of this plugin with new bug fixes and enhancements which it will also ignore the admin dashboard.
